### ISSUE TITLE
Could not find launcher jar: /home/master/activator-kafka-spark-streaming/libexec/activator-launch-1.3.10.jar

### ISSUE THREAD

**Issue by cutd** [knoldus/activator-kafka-spark-streaming#1]
after `bin/activator clean compile`  
`Could not find launcher jar: ~/activator-kafka-spark-streaming/libexec/activator-launch-1.3.10.jar`

**Comment by PKOfficial** [comment]
Hi @cutd ,
Thanks for raising the issue. I've fixed it. 
There was a file **activator-launch-1.3.10.jar** missing
